{
    "name": "VNOPTIC Products",
    "version": "16.0.1.0.0",
    "summary": "Lens & Optical product management",
    "author": "Your Company",
    "depends": ["product", "base"],
    "data": [
        'security/ir.model.access.csv',
        'data/product_group_type_data.xml',
        'views/product_status_views.xml',
        'views/product_group_views.xml',
        'views/product_warranty_views.xml',
        'views/product_creation_wizard_views.xml',
        'views/test_action.xml',
        'views/product_creation_wizard_action.xml',
        'views/product_template_views.xml',
        'views/product_lens_views.xml',
        'views/product_opt_views.xml',
        'views/product_fix_action.xml',
        'views/menu.xml',
    ],
    "installable": True,
    "application": True,
}
