{
    "name": "VNOPTIC Products",
    "version": "16.0.1.0.0",
    "summary": "Lens & Optical product management",
    "author": "Your Company",
    "depends": ["product", "base"],
    "data": [
        'security/ir.model.access.csv',
        'views/product_status_views.xml',
        'views/product_group_views.xml',
        'views/product_warranty_views.xml',
        'views/product_design_views.xml',
        'views/product_uv_views.xml',
        'views/product_cl_views.xml',
        'views/product_lens_index_views.xml',
        'views/product_material_views.xml',
        'views/product_coating_views.xml',
        'views/product_frame_views.xml',
        'views/product_frame_type_views.xml',
        'views/product_shape_views.xml',
        'views/product_ve_views.xml',
        'views/product_creation_wizard_views.xml',
        'views/product_temple_views.xml',
        'views/product_template_views.xml',
        'views/product_lens_views.xml',
        'views/product_opt_views.xml',
        'views/menu.xml',
    ],
    "installable": True,
    "application": True,
}
